Run CI tests on postgres instance (#3)
* Run CI tests on postgres instance

* Better doc

* Change host to localhost

* Try fix

* Add port mapping

* Add option for disabling retry in downgrade

* Pass correct port

* Update .github/workflows/ci.yml

* Remove comment

* Fix typo jobs -> job

* Add missing port

* Remove fetch-depth

* Don't use global env

* Apply suggestions from code review

* Update ci.yml

* Use global env for CI workflow

* Changes

* Add -s and -v flags to pytest

* Comment tests

* Comment

* Use AsyncClient instead of TestClient

* Fix errors

* Use await

* Change base_url

* Change URLs

* Add lifespan

* Update src/api/trainings_test.py

* Update src/api/trainings_test.py

* Fix upgrade error

error: trainingtype already exists

* Various fixes (yay!)

* Add comment in docs